[project]
name = "browser-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "fastapi-mcp>=0.3.7",
    "python-dotenv>=1.1.1",
    "selenium>=4.34.2",
]
